### PR TITLE
Dev standard library 1.4

### LINKED ISSUE #5: Update to standard library 1.4
Version 1.4 of the standard library was [released today]. Unfortunately, `Generic` doesn't seem to compile with it:

```
/build/source/src/Generic/Lib/Decidable.agda:60,1-85
Multiple definitions of dmap. Previous definition at
/nix/store/57x1n9aw7sgymjs8d9swbdhfa7sdm0f7-standard-library-1.4/src/Data/Product.agda:118,1-5
when scope checking the declaration
  dmap :
```

The reason seems to be that `Data.Product` exports a different function called `dmap`.

### PR DESCRIPTION
**Pull request by turion**
fixes #5

### CODE REVIEW

**Review by effectfully — APPROVED** [review]
Thanks a lot!

**Comment by turion** [comment]
You're welcome :) are you planning on releasing a new version? If yes, I can complete https://github.com/NixOS/nixpkgs/pull/98199 and add that new version to nixpkgs.

**Comment by turion** [comment]
Ah, I just realised I can probably do that without a release as well.

**Comment by effectfully** [comment]
I've added you as a collaborator. Does that give you the rights to release versions? If yes, feel free to do so anytime.

If not or you don't want to, then given

> Ah, I just realised I can probably do that without a release as well.

would releasing a new version still be helpful?

**Comment by turion** [comment]
I'll happily make a release :) what version should it be? 0.2?

**Comment by effectfully** [comment]
According to [SemVer](https://semver.org):

> What should I do if I update my own dependencies without changing the public API?

> That would be considered compatible since it does not affect the public API. Software that explicitly depends on the same dependencies as your package should have their own dependency specifications and the author will notice any conflicts. Determining whether the change is a patch level or minor level modification depends on whether you updated your dependencies in order to fix a bug or introduce new functionality. I would usually expect additional code for the latter instance, in which case it’s obviously a minor level increment.

I kind of like Haskell's [PVP](https://pvp.haskell.org), which is just like SemVer, but with an additional number prepended to the version string for the purpose of distinguishing between major releases and those that only break backwards compatibility (so SemVer [maps easily](https://gist.github.com/pbrisbin/4b31ce9cac904cb7ce515ee1fa50969d) to PVP).

So I think the version should be `0.1.0.1`.

**Pull request merged**
